#!/bin/bash
(
cd ~/boxes/precise-jessie
if [ "$1" == "-f" ]; then
    vagrant halt && vagrant destroy --force && rm Vagrantfile; vagrant init precise ~/Downloads/precise64.box && vagrant up
fi
cat<<EOF | vagrant ssh -- -A -T "sudo /bin/bash"
if [ -z "\$(which git)" ] ;then
    apt-get update
    apt-get install -y git
fi
[ ! -d /var/cache/git ] && mkdir -p /var/cache/git
if [ ! -d /var/cache/git/debbackporter ] ; then
    (cd /var/cache/git; git clone https://github.com/jameswhite/debbackporter)
fi
/var/cache/git/debbackporter/\$(lsb_release -sc)
EOF
)
