#!/bin/bash
# vagrant init precise http://files.vagrantup.com/precise64.box && vagrant up && vagrant ssh
# sudo su -
# alias doit='wget -qO precise "https://gist.githubusercontent.com/jameswhite/5ef1524e5d99904a0e65/raw/precise" ; . precise'

add_packages(){
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $*
}

dbuild_prepare(){
    apt-get update
    env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --force-yes -oDpkg::Options::="--force-confdef" -oDpkg::Options::="--force-confold"
    add_packages dpkg-dev debhelper javahelper po4a dh-autoreconf libbz2-dev liblzma-dev libselinux-dev cmake libnspr4-dev \
                 libnss3-dev openjdk-7-jdk libsvrcore-dev junit junit4 libjss-java libldap-java libcommons-codec-java | tee build-deps-deps-precise
    update-java-alternatives -s java-1.7.0-openjdk-amd64
}

# The build dependency nightmare begins...

dbuild_dogtag(){
    dbuild_prepare
    add_packages apache2-dev debhelper default-jdk libcommons-cli-java libcommons-io-java \
                 libcommons-lang-java libidm-console-framework-java libservlet3.0-java \
                 libtomcat7-java libxalan2-java libxerces2-java \
                 policycoreutils python-dev selinux-policy-dev velocity

    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' dh-systemd) lt 1.14 && dbuild_init-system-helpers
    dpkg  -l | grep "ii *apache2-dev" || dbuild_apache2-dev

    [ ! -d /opt/local/pkg/dogtag ] && mkdir -p /opt/local/pkg/dogtag
    [ ! -d /opt/local/src/dogtag ] && mkdir -p /opt/local/src/dogtag
    (
      cd /opt/local/src/dogtag
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0-2.dsc
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0.orig.tar.xz
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0-2.debian.tar.xz
      dpkg-source -x dogtag-pki_10.2.0-2.dsc
      (cd dogtag-pki-10.2.0; dpkg-checkbuilddeps 2>&1 | grep .) || \
        ( cd dogtag-pki-10.2.0; debian/rules binary && mv /opt/local/src/dogtag/*.deb /opt/local/pkg/dogtag )
    )
}

dbuild_dpkg(){ # (>= 1.17)
    add_packages debhelper flex libncursesw5-dev
    [ ! -d /opt/local/src/dpkg ] && mkdir -p /opt/local/src/dpkg
    (
      cd /opt/local/src/dpkg
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.3.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.3.tar.xz
      dpkg-source -x dpkg_1.17.5ubuntu5.3.dsc
    )
    ( cd /opt/local/src/dpkg/dpkg-1.17.5ubuntu5.3;  dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/dpkg/dpkg-1.17.5ubuntu5.3; debian/rules binary && dpkg -i /opt/local/src/dpkg/*.deb )
}

dbuild_debhelper(){
    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' dpkg) lt 1.17 && dbuild_dpkg
    [ ! -d /opt/local/src/debhelper ] && mkdir -p /opt/local/src/debhelper
    (
      cd /opt/local/src/debhelper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20131227ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20131227ubuntu1.tar.gz
      dpkg-source -x debhelper_9.20131227ubuntu1.dsc
      (cd debhelper-9.20131227ubuntu1/; dpkg-checkbuilddeps 2>&1 | grep .) || \
        (cd debhelper-9.20131227ubuntu1/; debian/rules binary && dpkg -i /opt/local/src/debhelper/debhelper_9.20131227ubuntu1_all.deb )
    )
}

dbuild_apache2-dev(){
    apt-get install -y debhelper libaprutil1-dev libapr1-dev libpcre3-dev liblua5.1-0-dev libxml2-dev
    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' debhelper) lt 9 && dbuild_debhelper
    dbuild-apr
    dbuild-apr-util
    [ ! -d /opt/local/src/apache2-dev ] && mkdir -p /opt/local/src/apache2-dev
    (
      cd /opt/local/src/apache2-dev
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10-1ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10-1ubuntu1.debian.tar.gz
      dpkg-source -x apache2_2.4.10-1ubuntu1.dsc
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10-9.dsc
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10.orig.tar.bz2
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10-9.debian.tar.xz
      # dpkg-source -x apache2_2.4.10-9.dsc
    )
    ( cd /opt/local/src/apache2-dev/apache2-2.4.10; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apache2-dev/apache2-2.4.10; debian/rules binary && dpkg -i /opt/local/src/apache2-dev/apache2-dev*.deb )
}

dbuild_init-system-helpers(){
    [ ! -d /opt/local/src/init-system-helpers ] && mkdir -p /opt/local/src/init-system-helpers
    (
      cd /opt/local/src/init-system-helpers
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.14.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.14.tar.gz
      dpkg-source -x init-system-helpers_1.14.dsc
    )
    ( cd /opt/local/src/init-system-helpers/init-system-helpers-1.14; dpkg-checkbuilddeps 2>&1 | grep . ) || \
        ( cd /opt/local/src/init-system-helpers/init-system-helpers-1.14; debian/rules binary && dpkg -i /opt/local/src/init-system-helpers/dh-systemd_1.14_all.deb )
}

dbuild_apr(){ # >= 1.5.0
    add_packages doxygen libsctp-dev
    [ ! -d /opt/local/src/apr ] && mkdir -p /opt/local/src/apr
    (
      cd /opt/local/src/apr
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1-3.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1-3.debian.tar.xz
      dpkg-source -x apr_1.5.1-3.dsc
    )
    ( cd /opt/local/src/apr/apr-1.5.1; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apr/apr-1.5.1; debian/rules binary && dpkg -i /opt/local/src/apr/*.deb)
}

dbuild_apr-util(){ # >= 1.5.0
    add_packages libdb-dev unixodbc-dev
    [ ! -d /opt/local/src/apr-util ] && mkdir -p /opt/local/src/apr-util
    (
      cd /opt/local/src/apr-util
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4-1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4-1.debian.tar.xz
      dpkg-source -x apr-util_1.5.4-1.dsc
    )
    ( cd /opt/local/src/apr-util/apr-util-1.5.4; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apr-util/apr-util-1.5.4; debian/rules binary && dpkg -i /opt/local/src/apr-util/*.deb)
}

dbuild_tomcatjss(){
    [ ! -d /opt/local/src/tomcatjss ] && mkdir -p /opt/local/src/tomcatjss
    (
      cd /opt/local/src/tomcatjss
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0-0ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0-0ubuntu1.debian.tar.gz
      dpkg-source -x tomcatjss_7.1.0-0ubuntu1.dsc
    )
    ( cd /opt/local/src/tomcatjss/tomcatjss-7.1.0; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/tomcatjss/tomcatjss-7.1.0; debian/rules binary && dpkg -i /opt/local/src/tomcatjss/*.deb)

}

dbuild_jackson-annotations(){
    add_packages maven-debian-helper default-jdk-doc libmaven-javadoc-plugin-java
    [ ! -d /opt/local/src/jackson-annotations ] && mkdir -p /opt/local/src/jackson-annotations
    (
      cd /opt/local/src/jackson-annotations
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2-1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2-1.debian.tar.gz
      dpkg-source -x jackson-annotations_2.2.2-1.dsc
    )
    ( cd /opt/local/src/jackson-annotations/jackson-annotations-2.2.2; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/jackson-annotations/jackson-annotations-2.2.2; debian/rules binary && dpkg -i /opt/local/src/jackson-annotations/*.deb)
}

dbuild_maven-debian-helper(){ # >= 1.6.5
    add_packages cdbs maven-ant-helper help2man maven-repo-helper libmaven-plugin-tools-java
    dbuild_maven-repo-helper
    [ ! -d /opt/local/src/maven-debian-helper ] && mkdir -p /opt/local/src/maven-debian-helper
    (
      cd /opt/local/src/maven-debian-helper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/m/maven-debian-helper/maven-debian-helper_1.6.6.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/m/maven-debian-helper/maven-debian-helper_1.6.6.tar.gz
      dpkg-source -x maven-debian-helper_1.6.6.dsc
    )
    ( cd /opt/local/src/maven-debian-helper/maven-debian-helper-1.6.6; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/maven-debian-helper/maven-debian-helper-1.6.6; debian/rules binary && dpkg -i /opt/local/src/maven-debian-helper/*.deb)
}

dbuild_maven-repo-helper(){ # >= 1.8.5
    [ ! -d /opt/local/src/maven-repo-helper ] && mkdir -p /opt/local/src/maven-repo-helper
    (
      cd /opt/local/src/maven-repo-helper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/m/maven-repo-helper/maven-repo-helper_1.8.5.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/m/maven-repo-helper/maven-repo-helper_1.8.5.tar.gz
      dpkg-source -x maven-repo-helper_1.8.5.dsc
    )
    ( cd /opt/local/src/maven-repo-helper/maven-repo-helper-1.8.5; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/maven-repo-helper/maven-repo-helper-1.8.5; debian/rules binary && dpkg -i /opt/local/src/maven-repo-helper/*.deb)
}

# + dogtag
#     + apache2-dev (one with Debian/Debhelper/Sequence/systemd.pm, so we grab 2.4.10-9)
#         + debhelper (>= 9.20131213~)
#           + libaprutil1-dev (>= 1.5.0)
#           + libapr1-dev (>= 1.5.0)
#           + libpcre3-dev
#           + liblua5.1-0-dev
#           + libxml2-dev
#     + default-jdk
#     + dh-systemd
#     + javahelper
#     + junit4
#     + libcommons-cli-java
#     + libcommons-codec-java
#     + libcommons-io-java
#     + libcommons-lang-java
#     + libidm-console-framework-java
#     + libjackson2-annotations-java
#     + libjss-java
#     + libldap-java
#     + libldap2-dev
#     + libnspr4-dev
#     + libnss3-dev
#     + libresteasy-java
#     + libservlet3.0-java
#     + libsvrcore-dev
#     + libtomcat7-java
#     + libtomcatjss-java (>= 7.1.0)
#     + libxalan2-java
#     + libxerces2-java
#     + pkg-config
#     + policycoreutils
#     + python-dev
#     + selinux-policy-dev
#     + velocity
