#!/bin/bash
# vagrant init precise http://files.vagrantup.com/precise64.box && vagrant up && \
# sudo su -
# alias doit='wget --no-cache -qO precise "https://gist.githubusercontent.com/jameswhite/5ef1524e5d99904a0e65/raw/precise"; MD5=$(md5sum precise | cut -b 1-32); echo $MD5 ; chmod 755 precise ; ./precise'

SELF=$0
BASEDIR=$(cd $(dirname $0); pwd);
BIN=${BASEDIR}/bin
export SELF BASEDIR
export PATH="$BIN:$PATH"
dbuild_prepare
dbuild dogtag-pki
