#!/bin/bash
export SELF=$0;
# vagrant init precise http://files.vagrantup.com/precise64.box && vagrant up && vagrant ssh
# sudo su -
# alias doit='wget -qO precise "https://gist.githubusercontent.com/jameswhite/5ef1524e5d99904a0e65/raw/precise" ; . precise'

add_packages(){
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $*
}

dbuild_prepare(){
    if [ ! -f .prepared ]; then
        apt-get update
        env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --force-yes -oDpkg::Options::="--force-confdef" -oDpkg::Options::="--force-confold"
        add_packages dpkg-dev debhelper javahelper po4a dh-autoreconf libbz2-dev liblzma-dev libselinux-dev cmake libnspr4-dev \
                     libnss3-dev openjdk-7-jdk libsvrcore-dev junit junit4 libjss-java libldap-java libcommons-codec-java | tee build-deps-deps-precise
        update-java-alternatives -s java-1.7.0-openjdk-amd64
        touch .prepared
    fi
}

files_for(){
    DSC_FILE="$1"
    echo "$(cat ${DSC_FILE} | sed -n '/^Files: *$/,$p' | sed -e '/^ *$/ q' | grep -v ".*:" | grep . | awk '{print $NF}' | tr '\n' ' ')"
}

dbuild(){
    HANDLE=$1
    DSC_URL="$(cat $SELF | grep "^${HANDLE}: " | awk '{print $NF}')"
    if [ ! -z "${DSC_URL}" ]; then
        SUFFIX="$2" # some dsc files break the convention and add a suffix to the build dir that isn't included in the dsc file
        NAME=$(echo "${DSC_URL}" | sed -e 's/.*\///' -e 's/_.*//')
        VERSION=$(echo "${DSC_URL}" | sed -e 's/.*\///' -e 's/.*_//' -e 's/-.*//' -e 's/.dsc$//')
        URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
        DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
        [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
        (
          cd /opt/local/src/${NAME}
          wget -nc ${DSC_URL}
          for file in $(files_for ${DSC_FILE}); do wget -nc "${URL_BASE}/$file"; done
          dpkg-source -x ${DSC_FILE}
        )
        BUILD_DEPS=$( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep "Unmet build dependencies: " | sed -e 's/.*Unmet build dependencies: //' | sed -e 's/([^)]*)//g' )
        if [ -z "${BUILD_DEPS}" ];then
            ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
        else
            for DEPENDENCY in ${BUILD_DEPS}; do
                dbuild ${DEPENDENCY}
            done
        fi
    else
        echo "Cannot determine the .dsc URL for ${HANDLE} in $SELF"
        exit 1;
    fi
}

dbuild_prepare
dbuild dpkg
dbuild debhelper
dbuild dogtag-pki

exit 0;

# The build dependency nightmare begins...
dogtag-pki:          https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0-2.dsc
dpkg:                http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.3.dsc
debhelper:           http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20131227ubuntu1.dsc
apache2-dev:         http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10-1ubuntu1.dsc
init-system-helpers: http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.14.dsc
apr:                 http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1-3.dsc
libldap2-dev:        http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/openldap_2.4.31-1+nmu2ubuntu11.dsc
libdb5.3-dev:        http://archive.ubuntu.com/ubuntu/pool/main/d/db5.3/db5.3_5.3.28-9.dsc

libaprutil1-dev:     http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4-1.dsc
tomcatjss:           http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0-0ubuntu1.dsc
jackson-annotations: http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2-1.dsc
maven-debian-helper: http://archive.ubuntu.com/ubuntu/pool/universe/m/maven-debian-helper/maven-debian-helper_1.6.6.dsc
maven-repo-helper    http://archive.ubuntu.com/ubuntu/pool/main/m/maven-repo-helper/maven-repo-helper_1.8.5.dsc
resteasy:            http://mirrors.kernel.org/ubuntu/pool/universe/r/resteasy/libresteasy-java_3.0.6-2_all.deb
apache-log4:         http://archive.ubuntu.com/ubuntu/pool/main/a/apache-log4j1.2/apache-log4j1.2_1.2.17-4ubuntu3.dsc
snakeyaml:           http://archive.ubuntu.com/ubuntu/pool/universe/s/snakeyaml/snakeyaml_1.12-2.dsc
scannotation:        http://archive.ubuntu.com/ubuntu/pool/universe/s/scannotation/scannotation_1.0.2+svn20110812-1.dsc
jaxb:                http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb/jaxb_2.2.5-1.dsc
javatools:           http://archive.ubuntu.com/ubuntu/pool/main/j/javatools/javatools_0.45ubuntu1.dsc
libcodemodel-java:   http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcodemodel-java/libcodemodel-java_2.6-1.dsc
dtd-parser:          http://archive.ubuntu.com/ubuntu/pool/universe/d/dtd-parser/dtd-parser_1.2~svn20110404-1.dsc
libargs4j-java:      http://archive.ubuntu.com/ubuntu/pool/universe/i/istack-commons/istack-commons_2.17-1.dsc
args4j:              http://archive.ubuntu.com/ubuntu/pool/universe/a/args4j/args4j_2.0.25-1.dsc
testng:              http://archive.ubuntu.com/ubuntu/pool/universe/t/testng/testng_6.8.7-2.dsc
jcommander:          http://archive.ubuntu.com/ubuntu/pool/universe/j/jcommander/jcommander_1.32-1.dsc
fastinfoset:         http://archive.ubuntu.com/ubuntu/pool/universe/f/fastinfoset/fastinfoset_1.2.12-1.dsc
xmlstreambuffer:     http://archive.ubuntu.com/ubuntu/pool/universe/x/xmlstreambuffer/xmlstreambuffer_1.5.1-1.dsc
stax-ex:             http://archive.ubuntu.com/ubuntu/pool/universe/s/stax-ex/stax-ex_1.7.1-1.dsc
xsom:                http://archive.ubuntu.com/ubuntu/pool/universe/x/xsom/xsom_0+20110809-1.dsc
librelaxngcc-java:   http://archive.ubuntu.com/ubuntu/pool/universe/r/relaxngcc/relaxngcc_1.12-1.dsc
rngom:               http://archive.ubuntu.com/ubuntu/pool/universe/r/rngom/rngom_0+201103+svn20110406-1.dsc
txw2:                http://archive.ubuntu.com/ubuntu/pool/universe/t/txw2/txw2_0.1+20110809-1.dsc
jaxb-api:            http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb-api/jaxb-api_2.2.9-1.dsc
