#!/bin/bash

# vagrant init precise http://files.vagrantup.com/precise64.box && vagrant up && vagrant ssh
# sudo su -
# alias doit='wget -qO precise "https://gist.githubusercontent.com/jameswhite/5ef1524e5d99904a0e65/raw/precise" ; . precise'

add_packages(){
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" $*
}

dbuild_prepare(){
    apt-get update
    env DEBIAN_FRONTEND=noninteractive apt-get upgrade -y --force-yes -oDpkg::Options::="--force-confdef" -oDpkg::Options::="--force-confold"
    add_packages dpkg-dev debhelper javahelper po4a dh-autoreconf libbz2-dev liblzma-dev libselinux-dev cmake libnspr4-dev \
                 libnss3-dev openjdk-7-jdk libsvrcore-dev junit junit4 libjss-java libldap-java libcommons-codec-java | tee build-deps-deps-precise
    update-java-alternatives -s java-1.7.0-openjdk-amd64
}

# The build dependency nightmare begins...

dbuild_dogtag(){
echo "this is fucked"
exit 1;
    dbuild_prepare
    add_packages apache2-dev debhelper default-jdk libcommons-cli-java libcommons-io-java \
                 libcommons-lang-java libidm-console-framework-java libservlet3.0-java \
                 libtomcat7-java libxalan2-java libxerces2-java \
                 policycoreutils python-dev selinux-policy-dev velocity

    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' dh-systemd) lt 1.14 && dbuild_init-system-helpers
    dpkg  -l | grep "ii *apache2-dev" || dbuild_apache2-dev

    [ ! -d /opt/local/pkg/dogtag ] && mkdir -p /opt/local/pkg/dogtag
    [ ! -d /opt/local/src/dogtag ] && mkdir -p /opt/local/src/dogtag
    (
      cd /opt/local/src/dogtag
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0-2.dsc
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0.orig.tar.xz
      wget -nc https://launchpad.net/ubuntu/+archive/primary/+files/dogtag-pki_10.2.0-2.debian.tar.xz
      dpkg-source -x dogtag-pki_10.2.0-2.dsc
      (cd dogtag-pki-10.2.0; dpkg-checkbuilddeps 2>&1 | grep .) || \
        ( cd dogtag-pki-10.2.0; debian/rules binary && mv /opt/local/src/dogtag/*.deb /opt/local/pkg/dogtag )
    )
}

dbuild_dpkg(){ # (>= 1.17)
    add_packages debhelper flex libncursesw5-dev
    [ ! -d /opt/local/src/dpkg ] && mkdir -p /opt/local/src/dpkg
    (
      cd /opt/local/src/dpkg
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.3.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg_1.17.5ubuntu5.3.tar.xz
      dpkg-source -x dpkg_1.17.5ubuntu5.3.dsc
    )
    ( cd /opt/local/src/dpkg/dpkg-1.17.5ubuntu5.3;  dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/dpkg/dpkg-1.17.5ubuntu5.3; debian/rules binary && dpkg -i /opt/local/src/dpkg/*.deb )
}

dbuild_debhelper(){
    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' dpkg) lt 1.17 && dbuild_dpkg
    [ ! -d /opt/local/src/debhelper ] && mkdir -p /opt/local/src/debhelper
    (
      cd /opt/local/src/debhelper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20131227ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/d/debhelper/debhelper_9.20131227ubuntu1.tar.gz
      dpkg-source -x debhelper_9.20131227ubuntu1.dsc
      (cd debhelper-9.20131227ubuntu1/; dpkg-checkbuilddeps 2>&1 | grep .) || \
        (cd debhelper-9.20131227ubuntu1/; debian/rules binary && dpkg -i /opt/local/src/debhelper/debhelper_9.20131227ubuntu1_all.deb )
    )
}

dbuild_apache2-dev(){
    apt-get install -y debhelper libaprutil1-dev libapr1-dev libpcre3-dev liblua5.1-0-dev libxml2-dev
    dpkg --compare-versions $(/usr/bin/dpkg-query -W -f='${Version}' debhelper) lt 9 && dbuild_debhelper
    dbuild-apr
    dbuild-apr-util
    [ ! -d /opt/local/src/apache2-dev ] && mkdir -p /opt/local/src/apache2-dev
    (
      cd /opt/local/src/apache2-dev
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10-1ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache2/apache2_2.4.10-1ubuntu1.debian.tar.gz
      dpkg-source -x apache2_2.4.10-1ubuntu1.dsc
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10-9.dsc
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10.orig.tar.bz2
      # wget -nc http://ftp.de.debian.org/debian/pool/main/a/apache2/apache2_2.4.10-9.debian.tar.xz
      # dpkg-source -x apache2_2.4.10-9.dsc
    )
    ( cd /opt/local/src/apache2-dev/apache2-2.4.10; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apache2-dev/apache2-2.4.10; debian/rules binary && dpkg -i /opt/local/src/apache2-dev/apache2-dev*.deb )
}

dbuild_init-system-helpers(){
    [ ! -d /opt/local/src/init-system-helpers ] && mkdir -p /opt/local/src/init-system-helpers
    (
      cd /opt/local/src/init-system-helpers
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.14.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/i/init-system-helpers/init-system-helpers_1.14.tar.gz
      dpkg-source -x init-system-helpers_1.14.dsc
    )
    ( cd /opt/local/src/init-system-helpers/init-system-helpers-1.14; dpkg-checkbuilddeps 2>&1 | grep . ) || \
        ( cd /opt/local/src/init-system-helpers/init-system-helpers-1.14; debian/rules binary && dpkg -i /opt/local/src/init-system-helpers/dh-systemd_1.14_all.deb )
}

dbuild_apr(){ # >= 1.5.0
    add_packages doxygen libsctp-dev
    [ ! -d /opt/local/src/apr ] && mkdir -p /opt/local/src/apr
    (
      cd /opt/local/src/apr
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1-3.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr/apr_1.5.1-3.debian.tar.xz
      dpkg-source -x apr_1.5.1-3.dsc
    )
    ( cd /opt/local/src/apr/apr-1.5.1; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apr/apr-1.5.1; debian/rules binary && dpkg -i /opt/local/src/apr/*.deb)
}

dbuild_apr-util(){ # >= 1.5.0
    add_packages libdb-dev unixodbc-dev
    [ ! -d /opt/local/src/apr-util ] && mkdir -p /opt/local/src/apr-util
    (
      cd /opt/local/src/apr-util
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4-1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4.orig.tar.bz2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apr-util/apr-util_1.5.4-1.debian.tar.xz
      dpkg-source -x apr-util_1.5.4-1.dsc
    )
    ( cd /opt/local/src/apr-util/apr-util-1.5.4; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apr-util/apr-util-1.5.4; debian/rules binary && dpkg -i /opt/local/src/apr-util/*.deb)
}

dbuild_tomcatjss(){
    [ ! -d /opt/local/src/tomcatjss ] && mkdir -p /opt/local/src/tomcatjss
    (
      cd /opt/local/src/tomcatjss
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0-0ubuntu1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/t/tomcatjss/tomcatjss_7.1.0-0ubuntu1.debian.tar.gz
      dpkg-source -x tomcatjss_7.1.0-0ubuntu1.dsc
    )
    ( cd /opt/local/src/tomcatjss/tomcatjss-7.1.0; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/tomcatjss/tomcatjss-7.1.0; debian/rules binary && dpkg -i /opt/local/src/tomcatjss/*.deb)
}

dbuild_jackson-annotations(){
    add_packages maven-debian-helper default-jdk-doc libmaven-javadoc-plugin-java
    [ ! -d /opt/local/src/jackson-annotations ] && mkdir -p /opt/local/src/jackson-annotations
    (
      cd /opt/local/src/jackson-annotations
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2-1.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jackson-annotations/jackson-annotations_2.2.2-1.debian.tar.gz
      dpkg-source -x jackson-annotations_2.2.2-1.dsc
    )
    ( cd /opt/local/src/jackson-annotations/jackson-annotations-2.2.2; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/jackson-annotations/jackson-annotations-2.2.2; debian/rules binary && dpkg -i /opt/local/src/jackson-annotations/*.deb)
}

dbuild_maven-debian-helper(){ # >= 1.6.5
    add_packages cdbs maven-ant-helper help2man maven-repo-helper libmaven-plugin-tools-java
    dbuild_maven-repo-helper
    [ ! -d /opt/local/src/maven-debian-helper ] && mkdir -p /opt/local/src/maven-debian-helper
    (
      cd /opt/local/src/maven-debian-helper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/m/maven-debian-helper/maven-debian-helper_1.6.6.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/m/maven-debian-helper/maven-debian-helper_1.6.6.tar.gz
      dpkg-source -x maven-debian-helper_1.6.6.dsc
    )
    ( cd /opt/local/src/maven-debian-helper/maven-debian-helper-1.6.6; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/maven-debian-helper/maven-debian-helper-1.6.6; debian/rules binary && dpkg -i /opt/local/src/maven-debian-helper/*.deb)
}

dbuild_maven-repo-helper(){ # >= 1.8.5
    apt-get remove -y maven-debian-helper
    add_packages python-docutils libxmlunit-java
    [ ! -d /opt/local/src/maven-repo-helper ] && mkdir -p /opt/local/src/maven-repo-helper
    (
      cd /opt/local/src/maven-repo-helper
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/m/maven-repo-helper/maven-repo-helper_1.8.5.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/m/maven-repo-helper/maven-repo-helper_1.8.5.tar.gz
      dpkg-source -x maven-repo-helper_1.8.5.dsc
    )
    ( cd /opt/local/src/maven-repo-helper/maven-repo-helper-1.8.5; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/maven-repo-helper/maven-repo-helper-1.8.5; debian/rules binary && dpkg -i /opt/local/src/maven-repo-helper/*.deb)
}

dbuild_resteasy(){
echo "this is fucked"
exit 1
    add_packages glassfish-activation glassfish-javaee libjackson-json-java libjettison-java
    wget http://mirrors.kernel.org/ubuntu/pool/universe/r/resteasy/libresteasy-java_3.0.6-2_all.deb
    dpkg -i libresteasy-java_3.0.6-2_all.deb
# #    dbuild_jaxb
# #    dbuild_scannotation
#     [ ! -d /opt/local/src/resteasy ] && mkdir -p /opt/local/src/resteasy
#     (
#       cd /opt/local/src/resteasy
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/r/resteasy/resteasy_3.0.6-2.dsc
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/r/resteasy/resteasy_3.0.6.orig.tar.gz
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/r/resteasy/resteasy_3.0.6-2.debian.tar.xz
#       dpkg-source -x resteasy_3.0.6-2.dsc
#     )
#     ( cd /opt/local/src/resteasy/resteasy-3.0.6; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#       ( cd /opt/local/src/resteasy/resteasy-3.0.6; debian/rules binary && dpkg -i /opt/local/src/resteasy/*.deb)
# }

dbuild_apache-log4j(){
    add_packages libgnumail-java
    [ ! -d /opt/local/src/apache-log4j1.2 ] && mkdir -p /opt/local/src/apache-log4j1.2
    (
      cd /opt/local/src/apache-log4j1.2
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache-log4j1.2/apache-log4j1.2_1.2.17-4ubuntu3.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache-log4j1.2/apache-log4j1.2_1.2.17.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/main/a/apache-log4j1.2/apache-log4j1.2_1.2.17-4ubuntu3.debian.tar.gz
      dpkg-source -x apache-log4j1.2_1.2.17-4ubuntu3.dsc
    )
    ( cd /opt/local/src/apache-log4j1.2/apache-log4j1.2-1.2.17; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/apache-log4j1.2/apache-log4j1.2-1.2.17; debian/rules binary && dpkg -i /opt/local/src/apache-log4j1.2/*.deb)
}

dbuild_snakeyaml(){
    add_packages libmaven-bundle-plugin-java
    [ ! -d /opt/local/src/snakeyaml ] && mkdir -p /opt/local/src/snakeyaml
    (
      cd /opt/local/src/snakeyaml
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/snakeyaml/snakeyaml_1.12-2.dsc
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/snakeyaml/snakeyaml_1.12.orig.tar.gz
      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/snakeyaml/snakeyaml_1.12-2.debian.tar.gz
      dpkg-source -x snakeyaml_1.12-2.dsc
    )
    ( cd /opt/local/src/snakeyaml/snakeyaml-1.12; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/snakeyaml/snakeyaml-1.12; debian/rules binary && dpkg -i /opt/local/src/snakeyaml/*.deb)
}

# why does this one not build? fdsaf;lkjsadf;alsdkgj;lskhg;jklhsag
dbuild_scannotation(){
wget -nc http://mirrors.kernel.org/ubuntu/pool/universe/s/scannotation/libscannotation-java_1.0.2+svn20110812-1_all.deb
dpkg -i libscannotation-java_1.0.2+svn20110812-1_all.deb
#    add_packages libjavassist-java libservlet2.5-java
#    [ ! -d /opt/local/src/scannotation ] && mkdir -p /opt/local/src/scannotation
#    (
#      cd /opt/local/src/scannotation
#      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/scannotation/scannotation_1.0.2+svn20110812-1.dsc
#      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/scannotation/scannotation_1.0.2+svn20110812.orig.tar.xz
#      wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/s/scannotation/scannotation_1.0.2+svn20110812-1.debian.tar.xz
#      dpkg-source -x scannotation_1.0.2+svn20110812-1.dsc
#    )
#    ( cd /opt/local/src/scannotation/scannotation-1.0.2+svn20110812; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#      ( cd /opt/local/src/scannotation/scannotation-1.0.2+svn20110812; debian/rules binary && dpkg -i /opt/local/src/scannotation/*.deb )
}

dbuild_jaxb(){
    add_packages libargs4j-java libisorelax-java libjing-java libmsv-java
    wget http://mirrors.kernel.org/ubuntu/pool/universe/j/jaxb/libjaxb-java_2.2.5-1_all.deb
    dpkg -i libjaxb-java_2.2.5-1_all.deb
# #    dbuild_javatools
#     # libtxw2-java # >= 0.1+20110809
# #    dbuild_libcodemodel-java
#     # librelaxngcc-java
#     # librngom-java
#     # libdtd-parser-java
# #    dbuild_fastinfoset
#     # libistack-commons-java
# #    dbuild_jaxb-api
#     [ ! -d /opt/local/src/jaxb ] && mkdir -p /opt/local/src/jaxb
#     (
#       cd /opt/local/src/jaxb
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb/jaxb_2.2.5-1.dsc
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb/jaxb_2.2.5.orig.tar.xz
#       wget -nc http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb/jaxb_2.2.5-1.debian.tar.xz
#       dpkg-source -x jaxb_2.2.5-1.dsc
#     )
#     # That time you spent 4 days compiling dependencies just so this fucker won't build
#     ( cd /opt/local/src/jaxb/jaxb-2.2.5; rm -fr mkdir tools/lib/redist )
#     ( cd /opt/local/src/jaxb/jaxb-2.2.5; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#       ( cd /opt/local/src/jaxb/jaxb-2.2.5; debian/rules binary && dpkg -i /opt/local/src/jaxb/*.deb)
#
}

dbuild_javatools(){
    add_packages libtest-minimumversion-perl libtest-perl-critic-perl libtest-strict-perl \
                 gcj-jdk fastjar gcj-jre gcj-4.6-jdk gcj-4.6-jre libgcj12-dev ecj-gcj     \
                 libecj-java-gcj gcj-jre-headless gcj-4.6-jre ecj java-gcj-compat         \
                 gcj-4.6-jre-headless libgcj12-awt gcj-4.6-jre-headless binfmt-support
    NAME='javatools'
    VERSION='0.45'
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/main/j/javatools/javatools_0.45ubuntu1.dsc"
    FILES="javatools_0.45ubuntu1.tar.gz"
    SUFFIX='ubuntu1'
    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_libcodemodel-java(){
    add-packages ant-doc
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/libc/libcodemodel-java/libcodemodel-java_2.6-1.dsc"
    FILES="libcodemodel-java_2.6.orig.tar.xz libcodemodel-java_2.6-1.debian.tar.xz"
    NAME='libcodemodel-java'
    VERSION='2.6'
    SUFFIX=''
    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_dtd-parser(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/d/dtd-parser/dtd-parser_1.2~svn20110404-1.dsc"
    FILES="dtd-parser_1.2~svn20110404.orig.tar.xz dtd-parser_1.2~svn20110404-1.debian.tar.xz"
    NAME='dtd-parser'
    VERSION='1.2'
    SUFFIX='~svn20110404'

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_istack-commons(){
# [ERROR] BUILD FAILURE
# [INFO] ------------------------------------------------------------------------
# [INFO] TestNG support requires version 4.7 or above. You have declared version 6.x
# [INFO] ------------------------------------------------------------------------

wget http://mirrors.kernel.org/ubuntu/pool/universe/i/istack-commons/libistack-commons-java_2.17-1_all.deb
dpkg -i libistack-commons-java_2.17-1_all.deb

# libargs4j-java # >= 2.0.25

#    add_packages libbuild-helper-maven-plugin-java
#    # testng # >= 6
#    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/i/istack-commons/istack-commons_2.17-1.dsc"
#    FILES="istack-commons_2.17.orig.tar.xz istack-commons_2.17-1.debian.tar.xz"
#    NAME='istack-commons'
#    VERSION='2.17'
#    SUFFIX=''
#
#    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
#    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
#    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
#    (
#      cd /opt/local/src/${NAME}
#      wget -nc ${DSC_URL}
#      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
#      dpkg-source -x ${DSC_FILE}
#    )
#    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_args4j(){ # > 2.0.25
    add_packages libmockito-java libobjenesis-java
    wget http://mirrors.kernel.org/ubuntu/pool/universe/a/args4j/libargs4j-java_2.0.25-1_all.deb
    dpkg -i libargs4j-java_2.0.25-1_all.de
#    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/a/args4j/args4j_2.0.25-1.dsc"
#    FILES="args4j_2.0.25.orig.tar.gz args4j_2.0.25-1.debian.tar.gz"
#    NAME='args4j'
#    VERSION='2.0.25'
#    SUFFIX=''
#
#    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
#    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
#    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
#    (
#      cd /opt/local/src/${NAME}
#      wget -nc ${DSC_URL}
#      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
#      dpkg-source -x ${DSC_FILE}
#    )
#    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_testng(){
    add_packages libguice-java
    # jcommander
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/t/testng/testng_6.8.7-2.dsc"
    FILES="testng_6.8.7.orig.tar.xz testng_6.8.7-2.debian.tar.gz"
    NAME='testng'
    VERSION='6.8.7'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_jcommander(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/j/jcommander/jcommander_1.32-1.dsc"
    FILES="jcommander_1.32.orig.tar.gz jcommander_1.32-1.debian.tar.gz"
    NAME='jcommander'
    VERSION='1.32'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}


dbuild_fastinfoset(){
    dbuild_xmlstreambuffer
    dbuild_xsom
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/f/fastinfoset/fastinfoset_1.2.12-1.dsc"
    FILES="fastinfoset_1.2.12.orig.tar.xz fastinfoset_1.2.12-1.debian.tar.xz"
    NAME='fastinfoset'
    VERSION='1.2.12'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_xmlstreambuffer(){
    dbuild_stax-ex
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/x/xmlstreambuffer/xmlstreambuffer_1.5.1-1.dsc"
    FILES="xmlstreambuffer_1.5.1.orig.tar.gz xmlstreambuffer_1.5.1-1.debian.tar.xz"
    NAME='xmlstreambuffer'
    VERSION='1.5.1'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}


dbuild_stax-ex(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/s/stax-ex/stax-ex_1.7.1-1.dsc"
    FILES="stax-ex_1.7.1.orig.tar.xz stax-ex_1.7.1-1.debian.tar.xz"
    NAME='stax-ex'
    VERSION='1.7.1'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}
dbuild_xsom(){
    add_packages libjavacc-maven-plugin-java libmaven-antrun-plugin-java librelaxng-datatype-java
    dbuild_relaxngcc
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/x/xsom/xsom_0+20110809-1.dsc"
    FILES="xsom_0+20110809.orig.tar.xz xsom_0+20110809-1.debian.tar.xz"
    NAME='xsom'
    VERSION='0+20110809'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

    # librelaxngcc-java
dbuild_relaxngcc(){
    add_packages graphviz
    wget http://mirrors.kernel.org/ubuntu/pool/universe/r/relaxngcc/librelaxngcc-java_1.12-1_all.deb
#    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/r/relaxngcc/relaxngcc_1.12-1.dsc"
#    FILES="relaxngcc_1.12.orig.tar.xz relaxngcc_1.12-1.debian.tar.xz"
#    NAME='relaxngcc'
#    VERSION='1.12'
#    SUFFIX=''
#
#    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
#    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
#    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
#    (
#      cd /opt/local/src/${NAME}
#      wget -nc ${DSC_URL}
#      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
#      dpkg-source -x ${DSC_FILE}
#    )
#    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
#      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}


dbuild_jaxb-api(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/j/jaxb-api/jaxb-api_2.2.9-1.dsc"
    FILES="jaxb-api_2.2.9.orig.tar.xz jaxb-api_2.2.9-1.debian.tar.xz"
    NAME='jaxb-api'
    VERSION='2.2.9'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_rngom(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/r/rngom/rngom_0+201103+svn20110406-1.dsc"
    FILES="rngom_0+201103+svn20110406.orig.tar.xz rngom_0+201103+svn20110406-1.debian.tar.gz"
    NAME='rngom'
    VERSION='0+201103+svn20110406'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}

dbuild_txw2(){
    DSC_URL="http://archive.ubuntu.com/ubuntu/pool/universe/t/txw2/txw2_0.1+20110809-1.dsc"
    FILES="txw2_0.1+20110809.orig.tar.xz txw2_0.1+20110809-1.debian.tar.xz"
    NAME='txw2'
    VERSION='0.1+20110809'
    SUFFIX=''

    URL_BASE="$(echo ${DSC_URL} | sed -e 's/\/[^\/]*$//')"
    DSC_FILE="$(echo ${DSC_URL} | sed -e 's/.*\///')"
    [ ! -d /opt/local/src/${NAME} ] && mkdir -p /opt/local/src/${NAME}
    (
      cd /opt/local/src/${NAME}
      wget -nc ${DSC_URL}
      for file in ${FILES}; do  wget -nc "${URL_BASE}/$file"; done
      dpkg-source -x ${DSC_FILE}
    )
    ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; dpkg-checkbuilddeps 2>&1 | grep . ) || \
      ( cd /opt/local/src/${NAME}/${NAME}-${VERSION}${SUFFIX}; debian/rules binary && dpkg -i /opt/local/src/${NAME}/*.deb)
}
